1. Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida de matriz en la que cada elemento es una suma de elementos de las 2 matrices? (solo puede usar numpy como librería, si realiza la matriz con otro paquete el ejercicio no es válido)

In [16]:
#Importar la libreria
import numpy as np
#Lista vacia
A = []
#Matriz ejemplo de dimensiones iguales
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

#Ciclo de suma de las matrices
for i in range(len(a1)):
    a = a1[i] + a2[i]
    A.append(a)
#Imprimir la matriz
print(A)

[5, 7, 9]


2. Cree una matriz de identidad de dimensión 4.

In [18]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


3. Convierte una matriz numpy binaria (que contiene solo 0 y 1) en una matriz numpy booleana.

In [24]:
#Lista binaria y booleana
ListaBinaria = np.identity(3)
ListaBooleana = np.array(ListaBinaria, dtype=bool)
#Imprimir Resultado
print(ListaBinaria)
print(f"\n")
print(ListaBooleana)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[ True False False]
 [False  True False]
 [False False  True]]


4. Genere una secuencia de números en forma de matriz numpy de 0 a 100 con espacios de 2 números, por ejemplo: 0, 2, 4 ...

In [34]:
#Matriz de 200 elementos
arrayA = np.arange(200)
#Solo se mantienen los elementos pares, queda en 200 para que se terminen con 100 elementos
print(arrayA[(arrayA % 2 == 0)])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
